# Generated by Django 5.2.17 on 2026-10-03 02:52

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_industry'),
        ('orders', '0002_giftrequest_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(default=apps.orders.models.generate_trade_public_code, max_length=24, unique=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=150)),
                ('action_type', models.CharField(choices=[('campanha', 'Campanha'), ('premiacao', 'Premiação'), ('evento', 'Evento'), ('feirao', 'Feirão'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('delivery_place', models.CharField(default='CD Belford Roxo', max_length=190)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('solicitada', 'Aguardando aprovação'), ('compra_realizada', 'Compra aprovada'), ('aguardando_recebimento', 'Aguardando recebimento no CD'), ('recebido_cd', 'Recebido no CD'), ('pronta', 'Pronta para retirada'), ('retirado', 'Retirada parcial'), ('entregue', 'Entregue'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=32)),
                ('purchase_ticket_no', models.CharField(blank=True, max_length=50)),
                ('invoice_no', models.CharField(blank=True, max_length=60)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trade_requests', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_requests', to='catalog.industry')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação TRADE',
                'verbose_name_plural': 'solicitações TRADE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.traderequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TradeRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fisico', 'Produto físico'), ('voucher', 'Voucher'), ('cartao', 'Cartão pré-pago / crédito'), ('outro', 'Outro')], default='fisico', max_length=20)),
                ('qty_requested', models.PositiveIntegerField()),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('qty_delivered', models.PositiveIntegerField(default=0)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_request_items', to='catalog.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.traderequest')),
            ],
            options={
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('request', 'product'), name='unique_product_per_trade_request')],
            },
        ),
    ]
