# Generated by Django 5.2.17 on 2026-10-03 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_traderequest_traderequesthistory_traderequestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('received_by_name', models.CharField(max_length=150)),
                ('received_by_document', models.CharField(blank=True, max_length=30)),
                ('received_by_email', models.EmailField(blank=True, max_length=190)),
                ('received_by_phone', models.CharField(blank=True, max_length=30)),
                ('recipient', models.CharField(blank=True, max_length=150)),
                ('signature_data', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.traderequest')),
            ],
            options={
                'verbose_name': 'protocolo TRADE',
                'verbose_name_plural': 'protocolos TRADE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeDeliveryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.tradedelivery')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='orders.traderequestitem')),
            ],
        ),
    ]
