# Generated by Django 5.2.17 on 2026-10-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_tradedelivery_tradedeliveryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDeliverySequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
