# Generated by Django 5.2.17 on 2026-10-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('catalog', '0002_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='catalog.industry'),
        ),
    ]
