# Generated by Django 5.2.17 on 2026-10-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_industry'),
        ('inventory', '0002_stockexitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexitorder',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exit_orders', to='catalog.industry'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.industry'),
        ),
    ]
