# Generated by Django 5.2.17 on 2026-10-03 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_default_cd_positions(apps, schema_editor):
    database = schema_editor.connection.alias
    StockLocation = apps.get_model("inventory", "StockLocation")
    StockBalance = apps.get_model("inventory", "StockBalance")
    StockPosition = apps.get_model("inventory", "StockPosition")
    StockMovement = apps.get_model("inventory", "StockMovement")
    StockExitOrder = apps.get_model("inventory", "StockExitOrder")
    location, _ = StockLocation.objects.using(database).get_or_create(
        name="CD Belford Roxo",
        defaults={"kind": "cd", "is_active": True},
    )
    for balance in StockBalance.objects.using(database).all().iterator():
        if balance.quantity > 0:
            StockPosition.objects.using(database).get_or_create(
                product_id=balance.product_id,
                location_id=location.pk,
                defaults={"quantity": balance.quantity},
            )
    StockMovement.objects.using(database).filter(location__isnull=True).update(location_id=location.pk)
    StockExitOrder.objects.using(database).filter(location__isnull=True).update(location_id=location.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_industry'),
        ('inventory', '0003_stockexitorder_industry_stockmovement_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('cd', 'CD / depósito'), ('event', 'Evento / feirão'), ('other', 'Outro local')], default='other', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('transfer', 'Transferência')], max_length=20),
        ),
        migrations.AddField(
            model_name='stockexitorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_orders', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.stocklocation'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.stocklocation')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='catalog.industry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='catalog.product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocktransfer'),
        ),
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to='catalog.product')),
            ],
            options={
                'ordering': ['location__name', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='unique_product_location_position'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_position_non_negative')],
            },
        ),
        migrations.RunPython(backfill_default_cd_positions, migrations.RunPython.noop),
    ]
