import { useEffect, useState } from "react";
import { Boxes, Plus, Search } from "lucide-react";
import { PageHeader } from "../components/Card";
import { api } from "../lib/api";
import type { Product } from "../types";
import { useAuth } from "../context/AuthContext";
import { can } from "../lib/access";

export function CatalogPage() { const { user } = useAuth(); const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); useEffect(() => { api.products().then(setProducts).catch((err) => setError(err.message)); }, []); const filtered = products.filter((p) => `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())); return <section className="page"><PageHeader title="Catálogo" description="Gerencie os brindes disponíveis para a operação." action={can(user, "catalog.manage") && <button className="primary-button"><Plus size={16} />Novo produto</button>} />{error && <div className="alert error">{error}</div>}<div className="toolbar"><div className="search-field"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome ou SKU" /></div><span className="result-count">{filtered.length} itens</span></div><div className="table-panel"><table><thead><tr><th>Produto</th><th>SKU</th><th>Unidade</th><th>Estoque mínimo</th><th>Status</th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><div className="table-primary"><div className="table-icon"><Boxes size={16} /></div><div><strong>{product.name}</strong><small>{product.description || "Sem descrição"}</small></div></div></td><td><code>{product.sku}</code></td><td>{product.unit}</td><td>{product.minimum_stock}</td><td><span className={product.is_active ? "badge active" : "badge inactive"}>{product.is_active ? "Ativo" : "Inativo"}</span></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state">Nenhum produto encontrado.</div>}</div></section>; }
