# Generated by Django 5.2.17 on 2026-10-03 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'indústria',
                'verbose_name_plural': 'indústrias',
                'ordering': ['name'],
            },
        ),
    ]
